RuningString/RuningString/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('movie.urls', namespace='movie')),
]

RuningString/movie/urls.py
from django.urls import path
from . import views

app_name = 'movie'

urlpatterns = [
    path('', views.home, name='home'),
    path('last_files/', views.last_files, name='last_files'),
    path('<str:filepath>/', views.download_file, name='download_file'),

]

RuningString/movie/models.py
from django.db import models




class Text(models.Model):
    text = models.CharField(max_length=209, verbose_name='текст',
                            help_text='Здесь должен быть текст')
    files = models.FileField(upload_to='../tempVideo/')
    pub_date = models.DateTimeField(auto_now_add=True,
                                    verbose_name='дата публикации')

    def __str__(self):
        return self.text

    class Meta:
        ordering = ['-pub_date']

RuningString/movie/forms.py
from django import forms
from .models import Text


class TextForm(forms.ModelForm):

    class Meta:
        model = Text
        fields = ('text',)

RuningString/movie/views.py
import mimetypes

from django.http import HttpResponse
from django.shortcuts import render
from .video import create_video
from .forms import TextForm
from .models import *
from transliterate import translit

LIMIT_LAST_TEXT = 5


def home(request):

    if request.method == 'POST':
        form = TextForm(request.POST)

        if form.is_valid():
            form.save()
            create_video(request.POST['text'])
            text_file = translit(request.POST['text'], language_code='ru', reversed=True)
            return download_file(request, text_file)
    else:
        form = TextForm()

    return render(request, 'index.html', {'form': form})


def last_files(request):
    last_text = Text.objects.all()[:LIMIT_LAST_TEXT]
    return render(request, 'last_files.html',
                  {'last_text': last_text})


def download_file(request, filepath):
    filepath = translit(filepath, language_code='ru', reversed=True)
    fl_path = '../tempVideo/' + filepath + '.mp4'
    filename = filepath + '.mp4'
    fl = open(fl_path, 'rb')
    mime_type, _ = mimetypes.guess_type(fl_path)
    response = HttpResponse(fl, content_type=mime_type)
    response['Content-Disposition'] = "attachment; filename=%s" % filename
    return response

RuningString/templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
  <form action="{% url 'movie:home' %}" method="post">

    {% csrf_token %}
    {{form.as_p}}
      <button type="submit">Добавить</button>
  </form>

<h1> <a href="{% url 'movie:last_files' %}">Последние Записи</a> </h1>
</body>
</html>

RuningString/templates/last_files.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Последние файлы</title>
</head>
<body>
<h1> Последние Записи </h1>

    {% for t in last_text %}
             <article>
                <ul>
                  <li>
                   <a href="{% url 'movie:download_file' filepath=t.text%}">{{ t.text }}: {{ t.pub_date }}</a>
                    {{ t.text }}: {{ t.pub_date }}
                  </li>
                </ul>
              </article>
    {% endfor %}

</body>
</html>